version: '3'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - simrs-mongo:/data/db

volumes:
  simrs-mongo:
    driver: local

networks:
  simrs-net:
    external: true
